/**
 * Catalogo de emojis Unicode agrupado por categoria. Se insertan como caracter, no
 * como imagen: pesan cero y los dibuja la fuente del sistema. Las palabras clave
 * estan en castellano porque el buscador es para alumnado hispanohablante.
 */
export interface EmojiEntry {
  char: string;
  keywords: string;
}

export interface EmojiGroup {
  label: string;
  emojis: EmojiEntry[];
}

/** Atajo para declarar la lista sin repetir nombres de campo. */
const e = (char: string, keywords: string): EmojiEntry => ({ char, keywords });

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    label: 'Caras',
    emojis: [
      e('😀', 'sonrisa feliz contento cara'),
      e('😄', 'sonrisa alegre feliz'),
      e('😁', 'sonrisa dientes feliz'),
      e('🤣', 'risa carcajada gracioso'),
      e('😊', 'sonrisa timida amable'),
      e('🙂', 'sonrisa leve'),
      e('😍', 'amor corazon enamorado'),
      e('🥰', 'amor carino corazones'),
      e('😘', 'beso amor'),
      e('😎', 'gafas guay sol'),
      e('🤓', 'gafas empollon estudioso'),
      e('🤔', 'pensar duda pensativo'),
      e('😮', 'sorpresa asombro'),
      e('😲', 'asombro impresion'),
      e('😴', 'dormir sueno cansado'),
      e('😢', 'triste llorar lagrima'),
      e('😭', 'llorar triste desconsolado'),
      e('😡', 'enfado rabia enojado'),
      e('😱', 'miedo grito susto'),
      e('🤒', 'enfermo fiebre malo'),
      e('🥳', 'fiesta celebracion cumpleanos'),
      e('🤗', 'abrazo carino'),
      e('🙄', 'ojos hartazgo'),
      e('😉', 'guino complicidad'),
      e('🤫', 'silencio callar'),
      e('🤯', 'explotar mente asombro'),
      e('🥺', 'suplica pena ojitos'),
      e('😇', 'angel bueno santo'),
      e('🤠', 'vaquero sombrero'),
      e('👻', 'fantasma halloween'),
      e('🤖', 'robot maquina'),
      e('👽', 'alien extraterrestre'),
    ],
  },
  {
    label: 'Personas',
    emojis: [
      e('👋', 'hola saludo mano adios'),
      e('👍', 'bien pulgar aprobado'),
      e('👎', 'mal pulgar negativo'),
      e('👏', 'aplauso bravo'),
      e('🙌', 'celebrar manos arriba'),
      e('🤝', 'acuerdo apreton manos'),
      e('✌️', 'paz victoria'),
      e('👌', 'perfecto ok'),
      e('🙏', 'gracias por favor rezar'),
      e('💪', 'fuerza musculo'),
      e('✍️', 'escribir mano lapiz'),
      e('👀', 'ojos mirar'),
      e('🧠', 'cerebro pensar mente'),
      e('👶', 'bebe nino'),
      e('🧒', 'nino infancia'),
      e('👦', 'nino chico'),
      e('👧', 'nina chica'),
      e('🧑', 'persona adulto'),
      e('👨', 'hombre senor'),
      e('👩', 'mujer senora'),
      e('🧓', 'abuelo mayor anciano'),
      e('👨‍🏫', 'profesor maestro docente'),
      e('👩‍🏫', 'profesora maestra docente'),
      e('👨‍🔬', 'cientifico investigador'),
      e('👩‍🔬', 'cientifica investigadora'),
      e('👨‍🚀', 'astronauta espacio'),
      e('👩‍🚀', 'astronauta espacio'),
      e('👨‍⚕️', 'medico doctor'),
      e('👩‍⚕️', 'medica doctora'),
      e('👨‍🍳', 'cocinero chef'),
      e('🧑‍🌾', 'agricultor campo granja'),
      e('👮', 'policia agente'),
    ],
  },
  {
    label: 'Animales',
    emojis: [
      e('🐶', 'perro cachorro mascota'),
      e('🐱', 'gato gatito mascota'),
      e('🐭', 'raton'),
      e('🐹', 'hamster'),
      e('🐰', 'conejo'),
      e('🦊', 'zorro'),
      e('🐻', 'oso'),
      e('🐼', 'panda oso'),
      e('🐨', 'koala'),
      e('🐯', 'tigre'),
      e('🦁', 'leon'),
      e('🐮', 'vaca'),
      e('🐷', 'cerdo'),
      e('🐸', 'rana'),
      e('🐵', 'mono'),
      e('🐔', 'gallina pollo'),
      e('🐧', 'pinguino'),
      e('🐦', 'pajaro ave'),
      e('🦆', 'pato ave'),
      e('🦅', 'aguila ave'),
      e('🦉', 'buho lechuza'),
      e('🐺', 'lobo'),
      e('🐗', 'jabali'),
      e('🐴', 'caballo'),
      e('🦄', 'unicornio fantasia'),
      e('🐝', 'abeja insecto'),
      e('🦋', 'mariposa insecto'),
      e('🐌', 'caracol'),
      e('🐢', 'tortuga'),
      e('🐍', 'serpiente'),
      e('🐙', 'pulpo mar'),
      e('🐠', 'pez mar'),
      e('🐳', 'ballena mar'),
      e('🦈', 'tiburon mar'),
      e('🐊', 'cocodrilo'),
      e('🦖', 'dinosaurio trex'),
      e('🐘', 'elefante'),
      e('🦒', 'jirafa'),
      e('🦓', 'cebra'),
      e('🐜', 'hormiga insecto'),
    ],
  },
  {
    label: 'Naturaleza',
    emojis: [
      e('🌵', 'cactus planta desierto'),
      e('🌲', 'arbol pino bosque'),
      e('🌳', 'arbol bosque'),
      e('🌴', 'palmera playa'),
      e('🌱', 'brote planta semilla'),
      e('🌿', 'hierba hoja planta'),
      e('🍀', 'trebol suerte'),
      e('🍁', 'hoja otono arce'),
      e('🌺', 'flor hibisco'),
      e('🌻', 'girasol flor'),
      e('🌹', 'rosa flor'),
      e('🌷', 'tulipan flor'),
      e('🌸', 'flor cerezo primavera'),
      e('🌍', 'mundo tierra planeta'),
      e('🌞', 'sol dia'),
      e('🌙', 'luna noche'),
      e('⭐', 'estrella'),
      e('🌟', 'estrella brillo'),
      e('☁️', 'nube'),
      e('🌧️', 'lluvia nube'),
      e('⛈️', 'tormenta rayo'),
      e('❄️', 'nieve copo frio'),
      e('🌈', 'arcoiris colores'),
      e('🔥', 'fuego llama'),
      e('💧', 'agua gota'),
      e('🌊', 'ola mar agua'),
      e('🌋', 'volcan'),
      e('⛰️', 'montana'),
      e('🏝️', 'isla playa'),
      e('🪐', 'planeta saturno espacio'),
    ],
  },
  {
    label: 'Comida',
    emojis: [
      e('🍎', 'manzana fruta'),
      e('🍌', 'platano banana fruta'),
      e('🍇', 'uvas fruta'),
      e('🍓', 'fresa fruta'),
      e('🍊', 'naranja fruta'),
      e('🍉', 'sandia fruta'),
      e('🍍', 'pina fruta'),
      e('🥑', 'aguacate'),
      e('🥕', 'zanahoria verdura'),
      e('🌽', 'maiz mazorca'),
      e('🍅', 'tomate'),
      e('🥔', 'patata papa'),
      e('🍞', 'pan'),
      e('🧀', 'queso'),
      e('🥚', 'huevo'),
      e('🍕', 'pizza'),
      e('🍔', 'hamburguesa'),
      e('🌮', 'taco'),
      e('🍝', 'pasta espagueti'),
      e('🍚', 'arroz'),
      e('🍦', 'helado'),
      e('🍪', 'galleta'),
      e('🎂', 'tarta cumpleanos pastel'),
      e('🍫', 'chocolate'),
      e('🍬', 'caramelo dulce'),
      e('☕', 'cafe bebida'),
      e('🥛', 'leche vaso'),
      e('🧃', 'zumo jugo'),
      e('💧', 'agua'),
    ],
  },
  {
    label: 'Escuela',
    emojis: [
      e('📚', 'libros estudiar biblioteca'),
      e('📖', 'libro leer lectura'),
      e('📕', 'libro rojo'),
      e('📝', 'escribir nota apuntes'),
      e('✏️', 'lapiz escribir'),
      e('🖍️', 'cera crayon color'),
      e('🖌️', 'pincel pintar'),
      e('🎨', 'paleta arte pintura'),
      e('📐', 'escuadra geometria medir'),
      e('📏', 'regla medir'),
      e('✂️', 'tijeras cortar'),
      e('📌', 'chincheta marcar'),
      e('📎', 'clip sujetar'),
      e('🔍', 'lupa buscar investigar'),
      e('🔬', 'microscopio ciencia'),
      e('🔭', 'telescopio astronomia'),
      e('🧪', 'probeta quimica ciencia'),
      e('🧲', 'iman fisica'),
      e('🧮', 'abaco calcular matematicas'),
      e('🗺️', 'mapa geografia'),
      e('🧭', 'brujula orientacion'),
      e('🎓', 'graduacion birrete'),
      e('🏫', 'escuela colegio'),
      e('💡', 'idea bombilla'),
      e('❓', 'pregunta duda'),
      e('❗', 'exclamacion importante'),
      e('✅', 'correcto bien check'),
      e('❌', 'incorrecto mal cruz'),
      e('⚠️', 'aviso peligro atencion'),
      e('🔢', 'numeros contar'),
      e('🔤', 'letras abecedario'),
      e('💻', 'ordenador portatil'),
      e('⌨️', 'teclado escribir'),
      e('🖥️', 'ordenador pantalla'),
      e('📱', 'movil telefono'),
      e('🔋', 'bateria energia'),
    ],
  },
  {
    label: 'Actividades',
    emojis: [
      e('⚽', 'futbol balon deporte'),
      e('🏀', 'baloncesto deporte'),
      e('🏐', 'voleibol deporte'),
      e('🎾', 'tenis deporte'),
      e('🏊', 'natacion nadar'),
      e('🚴', 'bicicleta ciclismo'),
      e('🏃', 'correr atletismo'),
      e('🤸', 'gimnasia voltereta'),
      e('🥇', 'oro medalla primero'),
      e('🏆', 'trofeo copa ganar'),
      e('🎯', 'diana objetivo'),
      e('🎮', 'videojuego mando'),
      e('🎲', 'dado juego azar'),
      e('🧩', 'puzzle pieza'),
      e('🎭', 'teatro mascaras'),
      e('🎵', 'musica nota'),
      e('🎸', 'guitarra musica'),
      e('🥁', 'tambor bateria musica'),
      e('🎺', 'trompeta musica'),
      e('🎤', 'microfono cantar'),
      e('🎬', 'cine claqueta pelicula'),
      e('📷', 'camara foto'),
      e('🎥', 'video camara'),
      e('🎉', 'fiesta celebracion'),
      e('🎈', 'globo fiesta'),
      e('🎁', 'regalo sorpresa'),
    ],
  },
  {
    label: 'Objetos y viajes',
    emojis: [
      e('🚗', 'coche auto carro'),
      e('🚌', 'autobus bus'),
      e('🚲', 'bicicleta bici'),
      e('🛴', 'patinete'),
      e('🚂', 'tren locomotora'),
      e('✈️', 'avion volar viaje'),
      e('🚀', 'cohete espacio'),
      e('⛵', 'barco velero'),
      e('🚢', 'barco crucero'),
      e('🏠', 'casa hogar'),
      e('🏰', 'castillo'),
      e('⛺', 'tienda campana acampada'),
      e('🌉', 'puente'),
      e('🕐', 'reloj hora tiempo'),
      e('⏰', 'despertador alarma'),
      e('📅', 'calendario fecha'),
      e('💰', 'dinero bolsa'),
      e('🔑', 'llave abrir'),
      e('🔒', 'candado cerrado seguro'),
      e('📦', 'caja paquete'),
      e('✉️', 'carta sobre correo'),
      e('📢', 'megafono anuncio'),
      e('🔔', 'campana aviso'),
      e('💬', 'bocadillo hablar mensaje'),
      e('💭', 'pensamiento nube'),
      e('❤️', 'corazon amor rojo'),
      e('💙', 'corazon azul'),
      e('💚', 'corazon verde'),
      e('💛', 'corazon amarillo'),
      e('✨', 'brillo chispa magia'),
      e('💥', 'explosion choque'),
      e('🏁', 'meta bandera final'),
    ],
  },
];

/** Lista plana para el buscador. */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_GROUPS.flatMap((group) => group.emojis);
